### ISSUE TITLE
не те  ipsymbols

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_ip_address_helper#18]
ipsymbols='1234567890abcdefABCDEFGHIJKLMNOPQRSTUVWXYZ:'

WTF? разрешены только hex digits 0-9 a-f A-F

**Comment by ahreenah** [comment]
тут только они и есть. Не понимаю вопроса...

**Comment by Alexey-T** [comment]
В адресе надо разрешить только 0..9 a..f. А твоя константа разрешает все буквы.

**Comment by ahreenah** [comment]
@Alexey-T, зайдите в Discord пж
