### ISSUE TITLE
Problem with TABs

### ISSUE THREAD

**Issue by jczanfona** [medvosa/cuda_ip_address_helper#24]
I'm afraid it only runs if the IP is between spaces.
Could you also consider the possibility that it is between tabs?

**Comment by Alexey-T** [comment]
my fork of plugin is updated.
plugin is updated on AddonManager.

**Comment by jczanfona** [comment]
I've installed it with AddonManager...

**Comment by jczanfona** [comment]
Upsssss I'm going to update it!

**Comment by jczanfona** [comment]
Same result: If I put a space it runs
![image](https://user-images.githubusercontent.com/46503049/71032123-029b8d80-2115-11ea-94d3-738e5fe1b6cc.png)

**Comment by Alexey-T** [comment]
2nd address works here!

did you update plugin? restarted Cud?

**Comment by jczanfona** [comment]
Restart was the key!!
Thanks a lot
